package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN = 5
const PLAYER_ATTACK_MAX = 10
const PLAYER_HEAL_MIN = 10
const PLAYER_HEAL_MAX = 20

const MONSTER_ATTACK_MIN = 8
const MONSTER_ATTACK_MAX = 15

const SPECIAL_ATTACK_MULTIPLIER = 2
